apiVersion: v1
kind: Service
metadata:
  name: api-service 
  labels:
    app: todo-api 
spec:
  type: LoadBalancer 
  ports:
    - port: 80 
      targetPort: 3333 
      protocol: TCP
  selector:
    
    app: todo-api